version: '3.8'

services:
  elasticsearch:
    image:
      elasticsearch:7.17.22

    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
volumes:
  esdata: